# -*- coding: utf-8 -*-
"""atv6_Dict_bioavanc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JD063uhzMaZ8IP_8LtFQ6ar_dgnqBBEY
"""

fl = open("arquivo.txt", "r")

fl = fl.readlines()
string = fl[0].strip()

hash = dict()
palavras = string.split(" ")
for i in palavras:
  if i not in hash:
    hash[i] = 0
  hash[i] += 1

for k,v in hash.items():
  print(k, v)
