# -*- coding: utf-8 -*-
"""atv8_RNAsplicing_bioavanc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2Vc-j5QxRx5HvzGVncMY2z5sxMNnSeZ
"""

#pip install biopython

import Bio
from Bio import SeqIO
from Bio.Seq import MutableSeq

sequencias = []
for record in SeqIO.parse("rosalind_splc.fasta", "fasta"):
  sequencias.append(Bio.Seq.MutableSeq(record.seq))

#print(sequencias)
for i in range(1, len(sequencias)):
  sequencias[0] = sequencias[0].replace(str(sequencias[i]), "")

proteina = sequencias[0].translate()
print(proteina[0:len(proteina)-1])
