# -*- coding: utf-8 -*-
"""atv15_alinhamento_multiplo_bioavanc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14x4jQ0u1Kl4AYcdipT8sLtxfNL3AkjdA
"""

#pip install biopython

from Bio import SeqIO
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio.Align import substitution_matrices

sequences = []
matrix = substitution_matrices.load('BLOSUM62')

for record in SeqIO.parse("rosalind_clus.txt", "fasta"):
  sequences.append(record)


distances_matrix = {}
control_flag = 1
for i in sequences:
  distances_matrix[i.id] = {}


for i in range(0, len(sequences)):
  for j in range(control_flag, len(sequences)):
    a = pairwise2.align.globalds(sequences[i].seq, sequences[j].seq, matrix, -5, -5, score_only=True)
    distances_matrix[sequences[i].id][sequences[j].id] = a
  if i == 0:
    minimo = min(distances_matrix[sequences[i].id], key=distances_matrix[sequences[i].id].get)
  control_flag = control_flag + 1

print(minimo)
