# -*- coding: utf-8 -*-
"""Atv3_BioAvanc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oVkGHCF4TqVCBIa_-JOoxGLB-c4KBGhf
"""

a = 4029
b = 8954
c = 0
for i in range(a, b):
  if (i % 2) == 1:
    c += i
print(c)