# -*- coding: utf-8 -*-
"""atv13_scoring_matrix.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gQ_zAybWmVzszT13iiGGja0SxsGoT7tX
"""

#pip install biopython

from Bio import SeqIO
from Bio import pairwise2
from Bio.pairwise2 import format_alignment
from Bio.Align import substitution_matrices

record = SeqIO.parse("rosalind_glob.txt", "fasta")
seq1 = next(record).seq
seq2 = next(record).seq

matrix = substitution_matrices.load('BLOSUM62')
all_data = pairwise2.align.globalds(seq1, seq2, matrix, -5, -5)
score = pairwise2.align.globalds(seq1, seq2, matrix, -5, -5, score_only = True)
print(all_data[0].seqA)
print(int(score))