# -*- coding: utf-8 -*-
"""atv14_consensusprofile_bioavanc.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uLax8UTPe5XJOgCFpjamhIUj8m03Kv-b
"""

#pip install biopython

import Bio
from Bio import SeqIO

profile_matrix = {
    "A": [],
    "C": [],
    "G": [],
    "T": [],
}

sequencias = []
for record in SeqIO.parse("rosalind_constest.txt", "fasta"):
  sequencias.append(record.seq)

contA = 0
contC = 0
contG = 0
contT = 0
consensus_string = ""
for j in range(0, len(sequencias[0])):
  for i in range(0, len(sequencias)):
    if sequencias[i][j] == "A":
      contA += 1
    elif sequencias[i][j] == "C":
      contC += 1
    elif sequencias[i][j] == "G":
      contG += 1
    elif sequencias[i][j] == "T":
      contT += 1
  profile_matrix["A"].append(contA)
  profile_matrix["C"].append(contC)
  profile_matrix["G"].append(contG)
  profile_matrix["T"].append(contT)
  if max(contA, contC, contG, contT) == contA:
    consensus_string += "A"
  elif max(contA, contC, contG, contT) == contC:
    consensus_string += "C"
  elif max(contA, contC, contG, contT) == contG:
    consensus_string += "G"
  elif max(contA, contC, contG, contT) == contT:
    consensus_string += "T"
  contA = 0
  contC = 0
  contG = 0
  contT = 0

print(consensus_string)
print("A: ", end="")
for v in profile_matrix["A"]:
  print(v, end=" ")
print()
print("C: ", end="")
for v in profile_matrix["C"]:
  print(v, end=" ")
print()
print("G: ", end="")
for v in profile_matrix["G"]:
  print(v, end=" ")
print()
print("T: ", end="")
for v in profile_matrix["T"]:
  print(v, end=" ")
print()