# -*- coding: utf-8 -*-
"""atv16_assembly_quality_n50n75.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xMNa-KZb2G20B029GQUAGjQj48SjxDnb
"""

fl = open("rosalind_asmq.txt", "r")
sequences = fl.readlines()

lengths_sum = 0
for i in range(len(sequences)):
  sequences[i] = sequences[i].replace("\n", "")
  lengths_sum += len(sequences[i])

count = 0
N50 = False
N75 = False
for i in range(len(sequences)):
  max_seq = max(sequences, key=len)
  count += len(max_seq)
  sequences.remove(max_seq)
  if count >= lengths_sum/2 and N50 == False:
    N50 = True
    print(len(max_seq), end =" ")
  if count >= ((lengths_sum/4)*3) and N75 == False:
    N75 == True
    print(len(max_seq))
    break