# -*- coding: utf-8 -*-
"""Atv2_BioAvanc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1luLoG0ETNdysLrq1ctTJltLYinlPtyJN
"""

string = "JYoFKwTE70fSxVMJqWEa95CSZWABl0Oq7MochlusnSj2qEEsF9W36kkGAfKRzUzN7ZRc0ZMbhSllesR77U3iN0Ua0jVU6LnefYtWyA3mQpI2srQerythropusUP5iTFJdnMbCbogUjMocGiPQUbvhV96rpF17ycl3tM8Kqq5PwtMwpln17gr54xbIXU72TGBP."
a = 33
b = 39
c = 111
d = 120

print(string[a:b+1], string[c:d+1])