# -*- coding: utf-8 -*-
"""atv9_ORF_BioAvanc.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PGxOF7FlJvcTtPyEEnzJdb3ShPWkb_O3
"""

#pip install biopython

import Bio
from Bio import SeqIO
from Bio.Seq import Seq

record = SeqIO.parse("rosalind_orf.fasta", "fasta")

seq1 = next(record).seq
seq2 = seq1.reverse_complement()


frames123 = []
frames456 = []
for i in range(0, 3):
    if len(seq1[i:]) % 3 == 0:
        frames123.append(seq1[i:].translate())
        frames456.append(seq2[i:].translate())
    elif len(seq1[i:]) % 3 == 1:
        frames123.append((seq1[i:]+Seq("NN")).translate())
        frames456.append((seq2[i:]+Seq("NN")).translate())
    elif len(seq1[i:]) % 3 == 2:
        frames123.append((seq1[i:]+Seq("N")).translate())
        frames456.append((seq2[i:]+Seq("N")).translate())    
frames = frames123+frames456


proteinas_potenciais = []
for i in range(len(frames)):
  for j in range(len(frames[i])):
    if frames[i][j] == "M" and frames[i].find("*", j) != -1:
      proteinas_potenciais.append(frames[i][j:frames[i].find("*", j)])
proteinas_potenciais = list(set(proteinas_potenciais))

for i in proteinas_potenciais:
  print(i)
