# -*- coding: utf-8 -*-
"""atv11_base_filtration_quality.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1h37A1Noay3OHgSmDc3zksbK8QLtxV7Ln
"""

#pip install biopython

import Bio
from Bio import SeqIO


fl = open("rosalind_bfil.fastq", "r")
lines = fl.readlines()
limite = int(lines[0])
fl.close()
fasta = open("rosalind_bfil.fastq", "w")
for i in range(1, len(lines)):
  fasta.write(lines[i])
fasta.close()

records = []
for record in SeqIO.parse("rosalind_bfil.fastq", "fastq"):
  records.append(record)
leituras = []
for record in records:
  leituras += record.format("fastq").split()

i = 1
j = 3
for record in records:
  while record.letter_annotations["phred_quality"][0] < limite:
    del(record.letter_annotations["phred_quality"][0])
    leituras[i] = leituras[i][1:]
    leituras[j] = leituras[j][1:]
  while record.letter_annotations["phred_quality"][len(record.letter_annotations["phred_quality"])-1] < limite:
    del(record.letter_annotations["phred_quality"][len(record.letter_annotations["phred_quality"])-1])
    leituras[i] = leituras[i][:len(record.letter_annotations["phred_quality"])]
    leituras[j] = leituras[j][:len(record.letter_annotations["phred_quality"])]
  i = i + 4
  j = j + 4

resposta = open("atv11_output.txt", "w")
for i in range(len(leituras)):
  leituras[i] = leituras[i] + "\n"
  resposta.write(leituras[i])
resposta.close()



